FROM python:latest

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY backend .

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && gunicorn yandexdisc.wsgi:application --bind 0.0.0.0:8000"]